//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Accounting.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AccountingParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IAccountingListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AccountingParser.accounting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccounting([NotNull] AccountingParser.AccountingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AccountingParser.accounting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccounting([NotNull] AccountingParser.AccountingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AccountingParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] AccountingParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AccountingParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] AccountingParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AccountingParser.employee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmployee([NotNull] AccountingParser.EmployeeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AccountingParser.employee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmployee([NotNull] AccountingParser.EmployeeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AccountingParser.amount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmount([NotNull] AccountingParser.AmountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AccountingParser.amount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmount([NotNull] AccountingParser.AmountContext context);
}
